# Generated by Django 4.1.3 on 2023-08-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_rdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
