# Generated by Django 4.1.3 on 2023-08-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_movie_movie_rdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(blank=True, choices=[('IN CINEMAS', 'In Cinema'), ('COMING SOON', 'Coming Soon')], max_length=100, null=True),
        ),
    ]
