# Generated by Django 4.1.3 on 2023-09-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bookings_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='date',
        ),
    ]
